logs:
  level: "debug"

database:
  DSN: "diagnostics.db"
  # type: "postgres"
  # user: "your_db_user"
  # password: "your_db_password"
  # host: "localhost"
  # port: "5432"

api:
  port: "8050"
  jwt_secret: "your_jwt_secret"
