logs:
  # level: "info"

database:
  type: "postgres"
  DSN: "diagnostics"
  user: "your_db_user"
  password: "your_db_password"
  host: "localhost"
  port: "5432"

api:
  port: "8010"
  jwt_secret: "your_jwt_secret"
